{% set name = "spirv-tools" %}
{% set version = "2023.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/KhronosGroup/SPIRV-Tools/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 7416cc8a98a10c32bacc36a39930b0c5b2a484963df5d68f388ed7ffee1faad3

  - url: https://github.com/KhronosGroup/SPIRV-Headers/archive/refs/tags/sdk-1.3.243.0.tar.gz
    sha256: 16927b1868e7891377d059cd549484e4158912439cf77451ae7e01e2a3bcd28b
    folder: external/spirv-headers

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make    # [unix]
    - ninja   # [win]
  host:
  run:

test:
  commands:
    - spirv-as -h

about:
  home: https://github.com/KhronosGroup/SPIRV-Tools
  license: Apache-2.0
  license_file: LICENSE
  summary: The SPIR-V Tools project provides an API and commands for processing SPIR-V modules.

extra:
  recipe-maintainers:
    - isuruf
